"""Create initial schema

Revision ID: 26c86a78fdd1
Revises: 
Create Date: 2026-05-25 13:06:44.944315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from infrastructure.schemas import MoneyType


# revision identifiers, used by Alembic.
revision: str = '26c86a78fdd1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scooters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('CITY', 'MOUNTAIN', 'KIDS', name='scootercategory'), nullable=False),
    sa.Column('daily_rate', MoneyType(), nullable=False),
    sa.Column('deposit', MoneyType(), nullable=False),
    sa.Column('condition', sa.Enum('EXCELLENT', 'GOOD', 'WORN', name='scootercondition'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('rentals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scooter_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('price_for_period', MoneyType(), nullable=False),
    sa.Column('total_price', MoneyType(), nullable=False),
    sa.Column('deposit_amount', MoneyType(), nullable=False),
    sa.Column('status', sa.Enum('RESERVED', 'ACTIVE', 'RETURNED', 'CANCELLED', name='rentalstatus'), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('returned_on', sa.DateTime(), nullable=True),
    sa.Column('cancelled_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scooter_id'], ['scooters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rentals')
    op.drop_table('scooters')
    # ### end Alembic commands ###
